### ISSUE TITLE
LanguageTool Api reference in gramma.js

### ISSUE THREAD

**Issue by pielonet** [ONLYOFFICE/plugin-grammalecte#3]
Hi,

I found a reference to the LanguageTool API in `scripts/gramma.js` :

```
var serviceUrl  = "https://languagetool.org/api/v2/check";
```
I thought Grammalecte plugin for Onlyoffice used a self hosted Grammalect service. Thus making no external call to any API service.. So what is this reference here for ?

Kind regards,
Thierry

**Comment by ShockwaveNN** [comment]
This issue should be resolved in current stable

**Comment by trofim24** [comment]
Fixed
